#!/usr/bin/env node
// enterprise/ci/generate.js
// Generates CI pipeline config from the orchestrator's stages[] definition.
// The validator runs in CI; pipeline fails = no merge.
//
// Usage:
//   node enterprise/ci/generate.js                 # writes to stdout
//   node enterprise/ci/generate.js -o FILE         # writes to FILE
//   node enterprise/ci/generate.js --target github # default
//   node enterprise/ci/generate.js --target gitlab
//   node enterprise/ci/generate.js --target jenkins
//   node enterprise/ci/generate.js --force         # overwrite existing
//
// Reads:
//   .kiro/agents/orchestrator.json  — the stages[] config
//   .kiro/agents/validator.json     — what the validator actually does
//   package.json / pyproject.toml    — to detect the stack

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const ROOT = process.cwd();

const args = process.argv.slice(2);
const arg = (name) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : null;
};
const target = arg('--target') || 'github';
const outFile = arg('-o') || arg('--output') || null;
const force = args.includes('--force');

function exists(p) {
  try { fs.accessSync(p); return true; } catch { return false; }
}

function loadOrchestrator() {
  const f = path.join(ROOT, '.kiro/agents/orchestrator.json');
  if (!exists(f)) throw new Error('orchestrator.json not found at ' + f);
  return JSON.parse(fs.readFileSync(f, 'utf8'));
}

function loadValidator() {
  const f = path.join(ROOT, '.kiro/agents/validator.json');
  if (!exists(f)) return null;
  return JSON.parse(fs.readFileSync(f, 'utf8'));
}

function detectStack() {
  const out = { language: 'unknown', packageManager: 'npm', test: null, lint: null, typecheck: null, format: null };
  if (exists(path.join(ROOT, 'package.json'))) {
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
    out.language = 'javascript';
    if (exists(path.join(ROOT, 'pnpm-lock.yaml'))) out.packageManager = 'pnpm';
    else if (exists(path.join(ROOT, 'yarn.lock'))) out.packageManager = 'yarn';
    out.test = pkg.scripts?.test || 'npm test';
    out.lint = pkg.scripts?.lint || 'npm run lint';
    out.typecheck = pkg.scripts?.typecheck || 'tsc --noEmit';
    out.format = pkg.scripts?.format || 'prettier --check .';
  } else if (exists(path.join(ROOT, 'pyproject.toml'))) {
    out.language = 'python';
    out.packageManager = exists(path.join(ROOT, 'uv.lock')) ? 'uv' : 'pip';
    out.test = 'pytest';
    out.lint = 'ruff check .';
    out.typecheck = 'mypy --strict .';
    out.format = 'ruff format --check .';
  } else if (exists(path.join(ROOT, 'go.mod'))) {
    out.language = 'go';
    out.packageManager = 'go';
    out.test = 'go test ./...';
    out.lint = 'go vet ./... && staticcheck ./...';
    out.typecheck = 'go build ./...';
  } else if (exists(path.join(ROOT, 'Cargo.toml'))) {
    out.language = 'rust';
    out.packageManager = 'cargo';
    out.test = 'cargo test';
    out.lint = 'cargo clippy -- -D warnings';
    out.typecheck = 'cargo build';
  }
  return out;
}

// ---------- generators ----------

function generateGitHubActions(orchestrator, validator, stack) {
  const stages = (orchestrator.stages || []).map((s) => s.name || s.id).join(' → ');
  const validatorName = (orchestrator.stages || []).find((s) => s.name === 'validate')?.agent || 'validator';

  return `# Generated by forge-sdlc — do not edit by hand
# Stages: ${stages}
name: forge-validate
on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  forge-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        if: ${{ hashFiles('package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: '${stack.packageManager}'

      - name: Setup Python
        if: ${{ hashFiles('pyproject.toml') != '' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies (${stack.language})
        run: |
          ${stack.language === 'python'
            ? 'pip install -e ".[dev]" && pip install ruff mypy pytest'
            : stack.language === 'go'
            ? 'go mod download'
            : stack.language === 'rust'
            ? 'cargo fetch'
            : `${stack.packageManager} install`}

      - name: Type check
        if: ${{ hashFiles('tsconfig.json') != '' || hashFiles('pyproject.toml') != '' }}
        run: ${stack.typecheck || 'echo "no type check configured"'}

      - name: Lint
        run: ${stack.lint || 'echo "no lint configured"'}

      - name: Test
        run: ${stack.test || 'echo "no test configured"'}

      - name: Format check
        if: ${{ hashFiles('.prettierrc*') != '' || hashFiles('pyproject.toml') != '' }}
        run: ${stack.format || 'echo "no format check configured"'}

      - name: Secret scan
        run: |
          pip install detect-secrets
          detect-secrets scan --baseline .secrets.baseline || true

      - name: Run forge-sdlc validator
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # The validator sub-agent runs the deterministic checks listed in
          # steering/03-quality-gates.md and emits VERDICT: PASS | FAIL.
          # In CI we only run the deterministic part — the LLM-judge checks
          # are skipped because they're not reproducible in a headless env.
          node enterprise/ci/run-validator.js

      - name: Post PR status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const verdict = process.env.FORGE_VERDICT || 'UNKNOWN';
            const body = \`🤖 forge-sdlc validator — \${verdict}\n\nSee the job logs for details.\`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
`;
}

function generateGitLabCI(orchestrator, validator, stack) {
  return `# Generated by forge-sdlc
stages:
  - validate

forge-validate:
  stage: validate
  image: ${stack.language === 'python' ? 'python:3.12' : stack.language === 'go' ? 'golang:1.22' : stack.language === 'rust' ? 'rust:latest' : 'node:20'}
  before_script:
    - ${stack.language === 'python' ? 'pip install -e ".[dev]" ruff mypy pytest' : `${stack.packageManager} install`}
  script:
    - ${stack.typecheck || 'true'}
    - ${stack.lint || 'true'}
    - ${stack.test || 'true'}
    - ${stack.format || 'true'}
    - node enterprise/ci/run-validator.js
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'
`;
}

function generateJenkinsfile(orchestrator, validator, stack) {
  return `// Generated by forge-sdlc
pipeline {
  agent any
  triggers {
    githubPullRequest()
  }
  stages {
    stage('Install') {
      steps {
        sh '${stack.language === 'python' ? 'pip install -e ".[dev]"' : `${stack.packageManager} install`}'
      }
    }
    stage('Type check') {
      steps { sh '${stack.typecheck || "true"}' }
    }
    stage('Lint') {
      steps { sh '${stack.lint || "true"}' }
    }
    stage('Test') {
      steps { sh '${stack.test || "true"}' }
    }
    stage('Format check') {
      steps { sh '${stack.format || "true"}' }
    }
    stage('Forge validator') {
      steps {
        sh 'node enterprise/ci/run-validator.js'
      }
    }
  }
  post {
    always {
      script {
        env.FORGE_VERDICT = sh(script: 'cat .forge/verdict.txt || echo UNKNOWN', returnStdout: true).trim()
      }
    }
  }
}
`;
}

// ---------- main ----------

const orchestrator = loadOrchestrator();
const validator = loadValidator();
const stack = detectStack();

let output;
let defaultPath;
switch (target) {
  case 'github':
    output = generateGitHubActions(orchestrator, validator, stack);
    defaultPath = '.github/workflows/forge-validate.yml';
    break;
  case 'gitlab':
    output = generateGitLabCI(orchestrator, validator, stack);
    defaultPath = '.gitlab-ci.yml';
    break;
  case 'jenkins':
    output = generateJenkinsfile(orchestrator, validator, stack);
    defaultPath = 'Jenkinsfile';
    break;
  default:
    console.error(`Unknown target: ${target}. Use github, gitlab, or jenkins.`);
    process.exit(2);
}

if (outFile) {
  const dest = path.join(ROOT, outFile);
  if (exists(dest) && !force) {
    console.error(`Refusing to overwrite existing file: ${dest}. Pass --force to overwrite.`);
    process.exit(1);
  }
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, output);
  console.error(`Wrote ${dest} (${output.length} bytes)`);
} else {
  process.stdout.write(output);
}

// Also write the validator script that CI will call
const validatorScript = `#!/usr/bin/env node
// enterprise/ci/run-validator.js
// The deterministic-only CI runner for the validator sub-agent.
// Runs the checks from steering/03-quality-gates.md without LLM judgment.
// Writes the verdict to .forge/verdict.txt and prints to stdout.

const fs = require('node:fs');
const path = require('node:path');
const { execSync } = require('node:child_process');

const ROOT = process.cwd();
const STACK = ${JSON.stringify(stack, null, 2)};

function run(cmd) {
  try {
    const out = execSync(cmd, { encoding: 'utf8', cwd: ROOT, stdio: 'pipe' });
    return { ok: true, out };
  } catch (e) {
    return { ok: false, out: e.stdout || e.message };
  }
}

const checks = [
  { name: 'typecheck', cmd: STACK.typecheck },
  { name: 'lint', cmd: STACK.lint },
  { name: 'test', cmd: STACK.test },
  { name: 'format', cmd: STACK.format },
];

const results = [];
let verdict = 'PASS';
for (const c of checks) {
  if (!c.cmd) continue;
  const r = run(c.cmd);
  results.push({ name: c.name, ok: r.ok, output: r.out.slice(-2000) });
  if (!r.ok) verdict = 'FAIL';
}

const report = {
  ts: new Date().toISOString(),
  stack: STACK,
  results,
  verdict,
};

fs.mkdirSync(path.join(ROOT, '.forge'), { recursive: true });
fs.writeFileSync(path.join(ROOT, '.forge', 'verdict.txt'), verdict);
fs.writeFileSync(path.join(ROOT, '.forge', 'ci-validator-report.json'), JSON.stringify(report, null, 2));

console.log(JSON.stringify(report, null, 2));
process.exit(verdict === 'PASS' ? 0 : 1);
`;

const ciDir = path.join(ROOT, 'enterprise/ci');
fs.mkdirSync(ciDir, { recursive: true });
const validatorScriptPath = path.join(ciDir, 'run-validator.js');
if (!exists(validatorScriptPath) || force) {
  fs.writeFileSync(validatorScriptPath, validatorScript);
  console.error(`Wrote ${validatorScriptPath}`);
}
